version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue_config.yml
          mapping: |
            # -- Unreal Plugin -- #
            src/XRFeitoriaUnreal/.* build-unreal-plugin true
            # -- tests -- #
            src/.* run-test true
            xrfeitoria/.* run-test true
            tests/.* run-test true
