name: release
on:
  pull_request:
  pull_request_target:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - uses: reviewdog/action-setup@v1
      #   with:
      #       reviewdog_version: latest

      - run: |
          echo "1234321" >> README.md

      - name: 'suggester / JSON & C++'
        uses: reviewdog/action-suggester@v1
