name: release
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - uses: reviewdog/action-setup@v1
      #   with:
      #       reviewdog_version: latest

      - run: |
          echo "1234321" >> README.md

      # - uses: reviewdog/action-suggester@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:

      - uses: googleapis/code-suggester@v2 # takes the changes from git directory
        with:
          command: pr
          upstream_owner: HaiyiMei
          upstream_repo: XRFeitoria
          description: 'This pull request is adding a LICENSE file'
          title: 'chore(license): add license file'
          message: 'chore(license): add license file'
          branch: my-branch
          git_dir: '.'
          labels: |
            bug
            priority: p1