name: release
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - uses: reviewdog/action-setup@v1
      #   with:
      #       reviewdog_version: latest

      - run: |
          echo "1234321" >> README.md

      # - uses: reviewdog/action-suggester@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:

      - uses: getsentry/action-git-diff-suggestions@main
        with:
          message: 'eslint made the following change'