name: release
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

permissions:
  contents: write
  checks: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: reviewdog/action-setup@v1

      - env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "1234321" >> README.md
          echo "Suggester is running"
          echo "CI_REPO_NAME: $CI_REPO_NAME"
          echo "CI_REPO_OWNER: $CI_REPO_OWNER"
          echo "CI_COMMIT: $CI_COMMIT"

          TMPFILE=$(mktemp)
          git diff >"${TMPFILE}"
          git stash -u

          export INPUT_TOOL_NAME=reviewdog-suggester
          export INPUT_LEVEL=warning
          export INPUT_FILTER_MODE=diff_context
          export INPUT_FAIL_ON_ERROR=false
          export INPUT_REVIEWDOG_FLAGS=true
          export INPUT_CLEANUP=true

          # shellcheck disable=SC2086
          reviewdog \
            -name="${INPUT_TOOL_NAME:-reviewdog-suggester}" \
            -f=diff \
            -f.diff.strip=1 \
            -reporter="github-pr-review" \
            -filter-mode="${INPUT_FILTER_MODE}" \
            -fail-on-error="${INPUT_FAIL_ON_ERROR}" \
            -level="${INPUT_LEVEL}" \
            ${INPUT_REVIEWDOG_FLAGS} <"${TMPFILE}"

          reviewdog \
            -name="${INPUT_TOOL_NAME:-reviewdog-suggester}" \
            -f=diff \
            -f.diff.strip=1 \
            -reporter="github-pr-review" \
            -filter-mode="${INPUT_FILTER_MODE}" \
            -fail-on-error="${INPUT_FAIL_ON_ERROR}" \
            -level="${INPUT_LEVEL}" \
            -diff="git diff"

      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -ignore 'SC2086' -ignore 'SC2129'
          fail_on_error: false
          level: error
          reporter: github-pr-review
      

      - name: Create Release
        run: reviewdog -diff="git diff origin/master" -fail-on-error=true