name: release
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - uses: reviewdog/action-setup@v1
      #   with:
      #       reviewdog_version: latest

      - run: |
          echo "1234321" >> README.md
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update README.md"

      - uses: reviewdog/action-suggester@v1
