name: unreal
on: push

jobs:
  unreal-build:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/epicgames/unreal-engine:dev-5.1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ACTIONS_PAT }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Miniconda, Python 3.10, and XRFeitoria
        run: |
          curl -sLo Miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash Miniconda.sh -b -p $HOME/miniconda
          echo "source $HOME/miniconda/bin/activate" >> $BASH_ENV
          source $BASH_ENV
          conda install -y python=3.10
          python -m pip install .
      - name: Build XRFeitoria for Unreal Engine
        run: |
          mkdir -p /home/ue4/project/src/dist
          python -m xrfeitoria.utils.publish_plugins build-unreal -u "/home/ue4/UnrealEngine/Engine/Binaries/Linux/UnrealEditor-Cmd"
          export XRFEITORIA__DIST_ROOT="/home/ue4/project/src"
          export XRFEITORIA__VERSION=`python -c "import xrfeitoria; print(xrfeitoria.__version__)"`
          rm -rf /home/ue4/project/src/dist/*-Source.zip  # remove source zip, cuz it's uploaded in the win build
          echo "#### Running Tests ####"
          # Can't run tests on non-gpu machine
          echo "Skipping tests on non-gpu machine"
